### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_variant_tensor'

### ISSUE THREAD

**Issue by ashishBT** [TensorSpeech/TensorFlowASR#171]
While training the model I am getting following error
`Traceback (most recent call last):
  File "train_subword_conformer.py", line 124, in <module>
    conformer_trainer.fit(train_dataset, eval_dataset, train_bs=args.tbs, eval_bs=args.ebs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_asr/runners/base_runners.py", line 308, in fit
    self.set_train_data_loader(train_dataset, train_bs, train_acs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_asr/runners/base_runners.py", line 124, in set_train_data_loader
    self.train_data_loader = self.strategy.experimental_distribute_dataset(self.train_data)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1059, in experimental_distribute_dataset
    return self._extended._experimental_distribute_dataset(dataset, options)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 529, in _experimental_distribute_dataset
    num_replicas_in_sync=self._num_replicas_in_sync)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 101, in get_distributed_dataset
    input_context=input_context)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 1011, in __init__
    num_replicas_in_sync)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 1065, in _make_rebatch_fn
    with ops.colocate_with(dataset._variant_tensor):  # pylint: disable=protected-access
AttributeError: 'NoneType' object has no attribute '_variant_tensor'
[ ]
`

**Comment by usimarit** [comment]
@ashishBT Could I see your `config.yml`?

**Comment by ashishBT** [comment]
I have just noticed that syntax of `config.yml` have been changed. I was using the OLD syntax. After using the NEW `config.yml` model is running successfully. Although model is producing error, when I set the eval and test file path instead of null
```
learning_config:
  train_dataset_config:
    use_tf: True
    augmentation_config:
      after:
        time_masking:
          num_masks: 10
          mask_factor: 100
          p_upperbound: 0.05
        freq_masking:
          num_masks: 1
          mask_factor: 27
    data_paths:
      - '/content/drive/MyDrive/Colab Notebooks/LibriSpeech-Short/train.tsv'
    tfrecords_dir: '/content/drive/MyDrive/Colab Notebooks/tfrecords'
    shuffle: True
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: train

  eval_dataset_config:
    use_tf: True
    data_paths: '/content/drive/MyDrive/Colab Notebooks/LibriSpeech-Short/dev.tsv'
    tfrecords_dir: '/content/drive/MyDrive/Colab Notebooks/tfrecords'
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: eval

  test_dataset_config:
    use_tf: True
    data_paths: '/content/drive/MyDrive/Colab Notebooks/LibriSpeech-Short/test.tsv'
    tfrecords_dir: '/content/drive/MyDrive/Colab Notebooks/tfrecords'
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: test
```
it is producing following errors:
```
Reading / ...
Traceback (most recent call last):
  File "train_subword_conformer.py", line 124, in <module>
    conformer_trainer.fit(train_dataset, eval_dataset, train_bs=args.tbs, eval_bs=args.ebs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_asr/runners/base_runners.py", line 309, in fit
    self.set_eval_data_loader(eval_dataset, eval_bs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_asr/runners/base_runners.py", line 138, in set_eval_data_loader
    self.eval_data = eval_dataset.create(eval_bs * self.strategy.num_replicas_in_sync)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_asr/datasets/asr_dataset.py", line 330, in create
    self.read_entries()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_asr/datasets/asr_dataset.py", line 104, in read_entries
    temp_lines = f.read().splitlines()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 122, in read
    return self._prepare_value(self._read_buf.read(length))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /; Is a directory
```
