### ISSUE TITLE
[CONFORMER] CANNOT reproduce conformer subword wer and cer listed in readme file

### ISSUE THREAD

**Issue by hsdrhsr** [TensorSpeech/TensorFlowASR#246]
The error rates shown in https://github.com/TensorSpeech/TensorFlowASR/tree/main/examples/conformer is 
```"Greedy: wer: 6.37933683 cer: 2.4757576 on test-clean; wer: 15.7308521 cer: 7.67273521 on test-other". ```
We can not reproduce this error rate. Our error rates are 
```"Greedy: wer: 11.6 cer 4.9 on test-clean with --pretrained=pretrained-subword-conformer/latest.h5 (download from google drive)"``` 
and 
```"Greedy: wer: 16.9 cer 0.078 on test-clean with --pretrained=None".```

Our config is the same as https://github.com/TensorSpeech/TensorFlowASR/blob/main/examples/conformer/config.yml:
```
speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: log_mel_spectrogram
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_frame: False

decoder_config:
  vocabulary: ./vocabularies/librispeech/librispeech_train_4_1030.subwords
  target_vocab_size: 1000
  max_subword_length: 10
  blank_at_zero: True
  beam_width: 0
  norm_score: True
  corpus_files:
    - /workspace/conformer/examples/conformer/train-clean-100.tsv

model_config:
  name: conformer
  encoder_subsampling:
    type: conv2d
    filters: 144
    kernel_size: 3
    strides: 2
  encoder_positional_encoding: sinusoid
  encoder_dmodel: 144
  encoder_num_blocks: 16
  encoder_head_size: 36
  encoder_num_heads: 4
  encoder_mha_type: relmha
  encoder_kernel_size: 32
  encoder_fc_factor: 0.5
  encoder_dropout: 0.1
  prediction_embed_dim: 320
  prediction_embed_dropout: 0
  prediction_num_rnns: 1
  prediction_rnn_units: 320
  prediction_rnn_type: lstm
  prediction_rnn_implementation: 2
  prediction_layer_norm: True
  prediction_projection_units: 0
  joint_dim: 320
  prejoint_linear: True
  joint_activation: tanh
  joint_mode: add

learning_config:
  train_dataset_config:
    use_tf: True
    augmentation_config:
      feature_augment:
        time_masking:
          num_masks: 10
          mask_factor: 100
          p_upperbound: 0.05
        freq_masking:
          num_masks: 1
          mask_factor: 27
    data_paths:
      - /workspace/conformer/examples/conformer/train-clean-100.tsv
    shuffle: True
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: train

  eval_dataset_config:
    use_tf: True
    data_paths:
      - /workspace/conformer/examples/conformer/dev-clean.tsv
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: eval

  test_dataset_config:
    use_tf: True
    data_paths:
      - /workspace/conformer/examples/conformer/test-clean.tsv
    tfrecords_dir: null
    shuffle: False
    cache: True
    buffer_size: 100
    drop_remainder: True
    stage: test

  optimizer_config:
    warmup_steps: 40000
    beta_1: 0.9
    beta_2: 0.98
    epsilon: 1e-9

  running_config:
    batch_size: 2
    num_epochs: 50
    checkpoint:
      filepath: /workspace/conformer/examples/conformer/checkpoints/train-subword-1030-pretrain-4gpus/{epoch:02d}.h5
      save_best_only: False
      save_weights_only: True
      save_freq: epoch
    states_dir: /workspace/conformer/examples/conformer/states/states_pretrain
    tensorboard:
      log_dir: /workspace/conformer/examples/conformer/tensorboard/train-subword-1030-pretrain-4gpus
      histogram_freq: 1
      write_graph: True
      write_images: True
      update_freq: epoch
      profile_batch: 2
```

We've used 4*V100 32G. Do we need to change other parameters? Could you please release the full command line to reproduce error rates in readme? Please help us figure it out. Thank you.
